keymaps/merge-conflicts.cson, stylesheets/merge-conflicts.atom-text-editor.less, stylesheets/merge-conflicts.less, stylesheets/variables.less
Adjust stylesheets according to the [upgrading guide](https://atom.io/docs/v0.173.0/upgrading/upgrading-your-ui-theme) so that lines are styled correctly with the shadow DOM enabled.
=> Shadow DOM

lib/conflict-marker.coffee, lib/conflict.coffee, lib/covering-view.coffee, lib/editor-adapter.coffee, lib/error-view.coffee, lib/merge-conflicts-view.coffee, lib/message-views.coffee, lib/resolver-view.coffee, package.json, spec/conflict-marker-spec.coffee, spec/side-view-spec.coffee
I wasn't actually using "atom-space-pen-views" for anything that wasn't just re-exported from space-pen, so I can just depend on space-pen myself and cut out the middleman. :scissors:
=> Depend on space-pen directly.

lib/conflict-marker.coffee, lib/covering-view.coffee, lib/merge-conflicts-view.coffee, lib/merge-conflicts.coffee, lib/navigation-view.coffee, lib/resolver-view.coffee, lib/side-view.coffee, spec/conflict-marker-spec.coffee, spec/navigation-view-spec.coffee, spec/side-view-spec.coffee
Because there's now an easy way to get a view from a model:
```coffeescript
view = atom.views.getView model
```
... I can get rid of all of the places where I'm awkwardly carrying around both, or passing the view around and yanking the model out when I need it.
=> Use Editor instead of EditorView.

lib/merge-conflicts-view.coffee, lib/merge-conflicts.coffee
The specs weren't catching this because they didn't use the top-level `detect()` method to set things up.
=> Pass package around properly.

CHANGELOG.md, docs/useful-test-cases.md, lib/covering-view.coffee, lib/navigation-view.coffee, lib/side-view.coffee
CoveringViews were cleaning up their event subscriptions in a `detached` hook. Unfortunately, an overlay decoration is detached from the DOM every time it scrolls off of the page!
This implements cleanup logic in a `cleanup` method which is explicitly invoked when the view is dismissed, or the TextEditor is destroyed.
Re #121
=> Control subscription cleanup in CoveringViews

CHANGELOG.md, lib/conflict-marker.coffee
If you invoke `merge-conflicts:next-unresolved` or `merge-conflicts:previous-unresolved` with:
1. No "active" conflict (meaning you have no cursors in a conflict area)
2. Conflicts exist in the requested navigation direction, but all of them have been resolved
Then the `ConflictMarker` will attempt to scroll you to a null target, which throws a stack trace.
Fixes #133.
=> Handle next or previous conflict navigation past the end

CHANGELOG.md, lib/conflict-marker.coffee, lib/conflict.coffee, lib/navigator.coffee, lib/side.coffee, spec/conflict-marker-spec.coffee
When conflict detection is either completed or exited, clean up any remaining markers.
Fixes #131.
=> Clean up resolved markers

CHANGELOG.md, lib/merge-conflicts-view.coffee
We need to use `=>` in `MergeConflictsView.sideResover` to reference `@pkg` properly.
Fixes #117.
=> Wrong sort of arrows

lib/covering-view.coffee
Get a clean test run with the `--one` flag.
=> Compatibility with atom --one API preview mode.

lib/merge-conflicts-view.coffee
Necessary because the Quit button is floated right.
Before:
After:
=> Apply clearfix to merge conflicts panel

CHANGELOG.md, keymaps/merge-conflicts.cson
Ctrl-M conflicts with bracket matcher.
Fixes #157.
=> Use alt-M instead of ctrl-M in the keymap.

CHANGELOG.md, lib/git-bridge.coffee, lib/view/error-view.coffee
I missed a deprecated call in the "git not found" error view. While I'm at it:
Fixes #148.
=> Correct the "git not found" error view

CHANGELOG.md, lib/git-bridge.coffee, lib/view/error-view.coffee, lib/view/merge-conflicts-view.coffee
If the active Project has no git repositories, show a friendlier error message.
Fixes #129.
=> Handle projects without git repositories

CHANGELOG.md, lib/conflicted-editor.coffee, lib/git-bridge.coffee, lib/merge-state.coffee, lib/view/merge-conflicts-view.coffee, lib/view/resolver-view.coffee, spec/conflicted-editor-spec.coffee, spec/git-bridge-spec.coffee, spec/view/merge-conflicts-view-spec.coffee, spec/view/resolver-view-spec.coffee
This makes the repository that you initially detect conflicts within "sticky." This avoids a few problems with opening editors from other projects and trying to stage resolutions for files in different ones.
=> More multiple repository work.

lib/view/merge-conflicts-view.coffee
ConflictedEditor already removes its markers on package completion or quit. The markers collection was redundant and causing crashes, like one of the ones seen in #119.
=> Remove "marker" maintenance

CHANGELOG.md, lib/view/merge-conflicts-view.coffee, styles/merge-conflicts.less
Use a scrollbar when you have more conflicted files than can be comfortably shown in the bottom panel.
Fixes #138.
=> [wip] Scroll the individual conflict marker list.

CHANGELOG.md, lib/view/merge-conflicts-view.coffee
This fixes another "Undefined is not a function" bug that crops up when you use the stage button in the MergeConflictsView, as referenced in #169.
=> GitBridge.add expects a repo, not a path.

styles/variables.less
Use transparency instead of mix() to allow selection to show through.
Reduce intensity slightly for better visibility.
=> Fix selection highlight display

CHANGELOG.md, lib/view/covering-view.coffee
This uses the `getVerticalScrollbarWidth` method on the element itself to avoid the removed and deprecated methods I was using before. Fixes #187, but imperfectly:
It looks like the scrollbar measurement is off somehow. I'd rather :shipit: this as-is because, well, at least it doesn't blow up on every package activation, even if it looks kind of funny.
=> verticallyScrollable is no longer a thing

CHANGELOG.md, lib/view/merge-conflicts-view.coffee
Looks like I missed a call when I refactored `GitBridge` to support multiple projects.
Fixes #182.
=> checkoutSide takes more arguments now.

lib/atom_merge, lib/mergetool.gitconfig
This addresses #43 
There's a simple script that spawns a wait loop and then throws the merge target into atom... you can then run merge-conflicts on that guy.
Once the file changes, the stat will update for the file, thus killing the script and git will throw up the next merge conflict. This can be very quick to use if you already have the repo open in atom, as you only need to run the merge-conflicts once, and then each file that atom opens will have the conflicts ready for you to change.
The only wuddyup I noticed was that env vars don't seem to be passed to bash atm... so I included a file ( `lib/mergetool.gitconfig` ) that should be sourceable for extending the local user's gitconfig.
As long as you get an absolute path for the atom_merge script or add it to the path, that guy should …
=> feat(cli): create git merge compatible mergetool script

lib/conflict.coffee, lib/conflicted-editor.coffee, lib/side.coffee, spec/conflict-spec.coffee, spec/fixtures/single-3way-diff-complex.txt, spec/fixtures/single-3way-diff.txt, styles/merge-conflicts.atom-text-editor.less, styles/variables.less
=> Add three-way merge markers support

lib/conflict.coffee
Sorry but previous PR #219 caused hang with below snippet...
```
<<<<<<< HEAD
AAA
||||||| merged common ancestors
BBB
>>>>>>> origin/master
```
It seems related to backtracking of regexp.
=> Fix hangs with broken conflict marker

lib/conflicted-editor.coffee, lib/view/side-view.coffee
Currently multiple undo operation is necessary to revert "Use Me" or other resolving commands.
This PR wraps them into single transaction and groups undo operation for resolving.
=> Transact resolve() to group undo operation

README.md, lib/git/common.js, lib/git/gitops.js, lib/git/shellout.js, lib/main.coffee, lib/merge-state.coffee, lib/view/merge-conflicts-view.coffee, lib/view/resolver-view.coffee, package.json, spec/conflicted-editor-spec.coffee, spec/git-shellout-spec.coffee, spec/util.coffee, spec/view/merge-conflicts-view-spec.coffee, spec/view/resolver-view-spec.coffee
In [Nuclide](http://nuclide.io/), we need to integrate such an awesome package for our mercurial repository (which currently doesn't come without all of nuclide).
Here are the changes I needed to do to get it working:
* **Service API**: Following Atom's [New Service API](http://blog.atom.io/2015/03/25/new-services-API.html), followed by Nuclide, I made the `merge-conflicts` compatible with that service API to register custom contexts.
* **Code**: The `Stage` term is specific to git, changed to `ResolveFile`
* **UI**: The hardcoded `Stage` message in the UI is also git-specific --> changed to a context-specifc `resolveText`
* **Priority**: Since you can easily have multiple roots with multiple repositories in an Atom window, the priority goes to the active file path and comes …
=> Register custom repository contexts

styles/merge-conflicts.less
Scrolling a large file with conflicts shows the "Use-me" overlays over the "conflicts" panel:
This can be easily solved by increasing the z-index from the "Conflicts panel". I added the `position: relative;` too to avoid possible breaks if the tag `<atom-panel />` ever gets its `position: relative;` removed.
=> Avoid "Use me" <atom-overlay> to scroll over conflicts panel

lib/git/shellout.js
On windows, paths may have forward or backward slashes. git under fake
unix environments in windows, like msys2, produces paths with forward
slashes.
We need to normalize those paths as they come out of git, so path
comparisons with atom paths (using backward slashes) work. Without this,
merge-conflict fails to mark conflicts on files in subdirectories due
to wrong slashes.
Additionally, it turns out that node's git-utils package wants forward
slashes. So, for git-utils methods, we use relativize on paths to convert
them to something git-utils likes.
This may fix #227 and #228.
I tried to test whether nodegit handles well windows paths, but atom errors
out with `USE_NODEGIT=1`. Is nodegit available on atom 1.7.x? Would we have
slash problems for windows there?
=> Normalize paths coming from git

lib/git/common.js, lib/git/gitops.js, lib/git/shellout.js, lib/main.coffee, lib/merge-state.coffee, lib/view/merge-conflicts-view.coffee
This extends #222 to support custom repository (hg in that case) detection of going into and out of rebase/merge conflict state and requesting to show or hide the merge conflicts UI accordingly.
These changes support multiple context providers & activating for the one with the highest priority that is indeed in a conflicting state.
Finally, it changes the `complete` & `quit` to be context-specific so that can be defined from Nuclide side to support automation of running the appropriate commands and remote development.
callback-to-promise and some minor simplifications are along the lines.
I'll be sharing the flow types defined for `merge-conflicts` APIs when I finish my changes on the nuclide side.
=> Custom repository contexts: show, hide, complete, quit and multi-context projects

lib/conflict.js
**Persistent** property was removed in Atom v1.9.0 and it generates deprecation warnings.
=> Fixes deprecation call to assign custom properties to a marker #262
